### PR TITLE
Should fix plot state problem in going from two-sided to one-sided

### PR DESCRIPTION
**Pull request by AlexanderLyNL**
Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/1632

### CODE REVIEW

**Comment by AlexanderLyNL** [comment]
I'm doing this blind, as I can't run a developer module.

**Comment by vandenman** [comment]
This does not fix the issue, I'll take a look in a separate PR.

**Comment by vandenman** [comment]
in particular, the labels for the plots are updated, but the values are not:

image

**Comment by vandenman** [comment]
So this PR should fix the issue once we merge https://github.com/jasp-stats/jaspRegression/pull/95.

**Review by vandenman — APPROVED** [review]

**Pull request merged**
