### PR TITLE
Bugfix: jaspTTests package was not specified when .bf10_normal() was called

### PR DESCRIPTION
**Pull request by akashrajkn**
Fixes jasp-stats/jasp-test-release#1223 
Fixes jasp-stats/jasp-test-release#1225
Fixes jasp-stats/jasp-test-release#1226

TODO: Add unit tests.

### CODE REVIEW

**Comment by TimKDJ** [comment]
You will need to add an export of this function to https://github.com/jasp-stats/jaspTTests/blob/master/NAMESPACE

**Comment by TimKDJ** [comment]
@akashrajkn are you going to work on this some more (i.e., add unit tests and adjust jaspTTests) or should I take over?

**Comment by akashrajkn** [comment]
I will work on it this week

**Comment by JorisGoosen** [comment]
@akashrajkn 
afbeelding

@TimKDJ can also fix it

**Comment by akashrajkn** [comment]
@TimKDJ Can you pick this up? I cannot work on it this week yet.

**Comment by vandenman** [comment]
I'm on it!

**Pull request closed without merging**
